feat: add store and checkbox for pokemoncard

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,10 +1,16 @@
-. "$(dirname "$0")/_/husky.sh"
+# . "$(dirname "$0")/_/husky.sh"
 
-npm run coverage 
+# npm run coverage 
 
-if [ $? -ne 0 ]; then
-  echo "Push canceled. Error in test"
-  exit 1
-fi
+# if [ $? -ne 0 ]; then
+#   echo "Push canceled. Error in test"
+#   exit 1
+# fi
 
-echo "All test is completed"
+# echo "All test is completed"
+
+#pre-commit 
+# . "$(dirname "$0")/_/husky.sh"
+
+#npm run test
+
